application:
  port: 8000
  host: "127.0.0.1"
  name: zero2prod
log:
  level: "info"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
